module.exports =
  routes:
    'GET /api/user/:id':
      controller: 'UserController'
      action: 'findOne'
    'GET /api/user':
      controller: 'UserController'
      action: 'find'
    'GET /api/cert':
      controller: 'CertController'
      action: 'find'
    'GET /api/my/cert':
      controller: 'CertController'
      action: 'findMy'
    'POST /api/cert':
      controller: 'CertController'
      action: 'sign'
    'PUT /api/cert/:id':
      controller: 'CertController'
      action: 'revoke'
